// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Voting.Infrastructure.ApplicationDbContext;

#nullable disable

namespace Voting.Infrastructure.Migrations
{
    [DbContext(typeof(VotingDbContext))]
    [Migration("20250416232032_MigInitialMigration")]
    partial class MigInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ParticipantVoting", b =>
                {
                    b.Property<Guid>("ParticipantsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VotingsId")
                        .HasColumnType("uuid");

                    b.HasKey("ParticipantsId", "VotingsId");

                    b.HasIndex("VotingsId");

                    b.ToTable("ParticipantVoting");
                });

            modelBuilder.Entity("Voting.Application.Entities.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Voting.Application.Entities.ParticipantVoting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VotingId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("VotingId");

                    b.ToTable("ParticipantVotings");
                });

            modelBuilder.Entity("Voting.Application.Entities.Voting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Votings");
                });

            modelBuilder.Entity("ParticipantVoting", b =>
                {
                    b.HasOne("Voting.Application.Entities.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Voting.Application.Entities.Voting", null)
                        .WithMany()
                        .HasForeignKey("VotingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Voting.Application.Entities.ParticipantVoting", b =>
                {
                    b.HasOne("Voting.Application.Entities.Participant", "Participant")
                        .WithMany("ParticipantVoting")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Voting.Application.Entities.Voting", "Voting")
                        .WithMany("ParticipantVotings")
                        .HasForeignKey("VotingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Voting");
                });

            modelBuilder.Entity("Voting.Application.Entities.Participant", b =>
                {
                    b.Navigation("ParticipantVoting");
                });

            modelBuilder.Entity("Voting.Application.Entities.Voting", b =>
                {
                    b.Navigation("ParticipantVotings");
                });
#pragma warning restore 612, 618
        }
    }
}
